### ISSUE TITLE
Why not 4 different files?

### ISSUE THREAD

**Issue by Mateiadrielrafael** [catppuccin/alacritty#10]
In my nix setup, I dynamically fetch different catppuccin themes from github. Having to manually edit a file doesn't really fit in what I want to do. For now, I just use some hacky string manipulation to automatically do this. The question is - is there any good reason not to have 4 different files like most other catppuccin themes?

Thanks in advance!

**Comment by nekowinston** [comment]
Good point, I'll have a look at reworking it, since it also helps with changing themes on the fly.

**Comment by andreasgrafen** [comment]
Just a quick elaboration: Initially I had 4 different files, but I figures that since Alacritty actually supports this more dynamic way of setting the theme it would be the better way to go with. Most other applications **do not** support this kind of config, hence the lack of similar structure for other ports.

To switch themes I just use `sed` in this case – which *could* be considered hacky, but I personally don't think it is.

That said, there is absolutely no point to be made against having separate files either. Do you wanna look into this @nekowinston? Otherwise I can quickly do that. c:

**Comment by nekowinston** [comment]
We investigated a couple of possible solutions, and I think the PR I opened is the cleanest one.

The `import:` mapping can be swapped out for hot-reloading (swapping flavours on the spot), which is why I think it should be a good fit.

Including the existing `catppuccin.yml` didn't work, because it would render anchors useless. Importing anchors from somewhere else, and then trying to use them inside the `alacritty.yml` doesn't work, likely because Alacritty already imports the parsed YAML.

I also gave a setup with `yq` a shot, using:
```bash
curl https://raw.githubusercontent.com/catppuccin/alacritty/637645e862edae51160b38248f02e0517b8682ee/catppuccin.yml | yq eval-all '. as $item ireduce ({}; . * $item )' - ~/.config/alacritty/alacritty.yml
```
Here are the [docs](https://mikefarah.gitbook.io/yq/operators/reduce#merge-all-yaml-files-together).
