### ISSUE TITLE
Transparency?

### ISSUE THREAD

**Issue by kcoderhtml** [catppuccin/alacritty#13]
Alacritty supports transparency and I think it would fit with the theme to add a little amount of it.
Here's an example with blur my shell:
![image](https://user-images.githubusercontent.com/92754843/197901304-ee219e0b-0d54-46a6-a784-b4af0434dc1e.png)
Here's without blur-my-shell opacity at 0.9:
![image](https://user-images.githubusercontent.com/92754843/197901530-cc00bc7f-5a66-4353-9a58-280883049245.png)

**Comment by isabelincorp** [comment]
Hey, thanks for the issue! Sadly, we aren't going to implement this since transparency is very opinionated (And the change to add this is super easy). 

Coming from someone that LOVES transparency, I love the idea, but it's more maintenance + themes should be as simple as possible and compliant to the [style guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md).

**Comment by andreasgrafen** [comment]
Furthermore the config files provided really only supply the colours. This enables everyone to use them with their own preferred config settings. c:

**Comment by nekowinston** [comment]
Our ports try to be non-opinionated when not relating to colors. If you're using Alacritty, I'd expect that the user knows how to configure their terminal, if they'd like to tweak some settings.

Am I missing something related to the Colorscheme here? AFAIK the only setting you'd have to set is
```yaml
import:
  - ~/.config/alacritty/catppuccin/catppuccin-frappe.yml

window:
  opacity: 0.9
```

If we include opacity in the import, the majority would have to reset it to 1 again.

**Comment by kcoderhtml** [comment]
That makes sense. @nekowinston that's exactly the configuration I'm using.

**Comment by nekowinston** [comment]
It's also at a point where I'm unsure if it's worth adding it to the FAQ, because it's just the default Alacritty config schema.

On the other hand, we could include stuff like *overriding* existing colors **from the import**, if that's possible, like I documented [here](https://github.com/catppuccin/wezterm#-faq) for WezTerm.
